<?php

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function main_banner_block_info() {
  return array(
      'main_banner' => array(
          'cache' => DRUPAL_NO_CACHE,
          'status' => TRUE,
          'info' => t('Main banner in header'),
          'region' => 'header',
      )
  );
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function main_banner_block_configure($delta = '') {
  $form = array();
  if ($delta == 'main_banner') {
    // If there is already an uploaded image display the image here.
    if ($image_fid = variable_get('main_banner_image_fid', FALSE)) {
      $image = file_load($image_fid);
      if($image->filemime == 'image/png' || $image->filemime == 'image/jpg'){
        $preview = theme('image', array('path' => $image->uri));
      } elseif($image->filemime == 'application/x-shockwave-flash'){
        $swf = new SWFObject(file_create_url($image->uri));
        $swf->height(90)
            ->width(728);
        $preview = theme('swfembed_embed', array('swf' => $swf));
      }
      $form['main_banner_image'] = array(
          '#markup' => $preview,
      );
    }
    // Use the #managed_file FAPI element to upload an image file.
    $form['main_banner_image_fid'] = array(
        '#title' => t('Image'),
        '#type' => 'managed_file',
        '#description' => t('The uploaded image will be displayed on header in main_banner block'),
        '#default_value' => variable_get('main_banner_image_fid', ''),
        '#upload_location' => 'public://main_banner/',
        '#upload_validators' => array(
            'file_validate_extensions' => array('png jpg swf')
        )
    );

    global $base_url;
    $form['main_banner_link'] = array(
        '#type' => 'textfield',
        '#title' => t('Link'),
        '#size' => 60,
        '#required' => true,
        '#default_value' => variable_get('main_banner_link', $base_url),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function main_banner_block_save($delta = '', $edit = array()) {
  // We need to save settings from the configuration form.
  // We need to check $delta to make sure we are saving the right block.
  if ($delta == 'main_banner') {
    // Have Drupal save the string to the database.
    variable_set('main_banner_link', $edit['main_banner_link']);

    // If fid is not 0 we have a valid file.
    if ($edit['main_banner_image_fid'] != 0) {
      // The new file's status is set to 0 or temporary and in order to ensure
      // that the file is not removed after 6 hours we need to change it's status
      // to 1. Save the ID of the uploaded image for later use.
      $file = file_load($edit['main_banner_image_fid']);
      $file->status = FILE_STATUS_PERMANENT;
      file_save($file);

      // When a module is managing a file, it must manage the usage count.
      // Here we increment the usage count with file_usage_add().
      file_usage_add($file, 'main_banner', 'sample_image', 1);

      // Save the fid of the file so that the module can reference it later.
      variable_set('main_banner_image_fid', $file->fid);
      drupal_set_message(t('The image @image_name was uploaded and saved', array('@image_name' => $file->filename, '@fid' => $file->fid)));
    }
    // If the file was removed we need to remove the module's reference to the
    // removed file's fid, and remove the file.
    elseif ($edit['main_banner_image_fid'] == 0) {
      // Retrieve the old file's id.
      $fid = variable_get('main_banner_image_fid', FALSE);
      $file = $fid ? file_load($fid) : FALSE;
      if ($file) {
        // When a module is managing a file, it must manage the usage count.
        // Here we decrement the usage count with file_usage_delete().
        file_usage_delete($file, 'main_banner', 'sample_image', 1);

        // The file_delete() function takes a file object and checks to see if
        // the file is being used by any other modules. If it is the delete
        // operation is cancelled, otherwise the file is deleted.
        file_delete($file);
      }

      // Either way the module needs to update it's reference since even if the
      // file is in use by another module and not deleted we no longer want to
      // use it.
      variable_set('main_banner_image_fid', FALSE);
      drupal_set_message(t('The image @image_name was removed.', array('@image_name' => $file->filename)));
    }
  }
  return;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function main_banner_block_view($delta = '') {
  if ($delta == 'main_banner') {
    $block['content'] = main_banner_contents($delta);
  }
  return $block;
}

function main_banner_contents($which_block) {
  if ($which_block == 'main_banner') {
    $fid = variable_get('main_banner_image_fid', FALSE);
    $file = $fid ? file_load($fid) : FALSE;
    if ($file) {
      global $base_url;
      $link_url = variable_get('main_banner_link', $base_url);
      if($file->filemime == 'image/png' || $file->filemime == 'image/jpg'){
        $preview = theme('image', array('path' => $file->uri));
      } elseif($file->filemime == 'application/x-shockwave-flash'){
        $swf = new SWFObject(file_create_url($file->uri));
        $swf->height(90)
            ->width(728);
        $preview = theme('swfembed_embed', array('swf' => $swf));
      }
      return array('#markup' => '<a href="' . $link_url . '" target="_blanck">' . $preview . '</a>');
    }
  }
}

/*
 * Implements hook_form_alter
 * 
 */

function main_banner_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'block_admin_configure' && $form['module']['#value'] == 'main_banner') {
    $form['settings']['title']['#type'] = 'hidden';
    $form['#validate'][] = 'main_banner_block_img_validate';
    //unset($form['visibility_title'], $form['visibility']);
    drupal_add_css('#edit-node-type{display:none;}', 'inline');
  }
}

/**
 * Verifies that the user supplied an image with the form..
 *
 * @ingroup image_example
 */
function main_banner_block_img_validate($form, &$form_state) {
  if (!isset($form_state['values']['main_banner_image_fid']) || !is_numeric($form_state['values']['main_banner_image_fid'])) {
    form_set_error('main_banner_image_fid', t('Please select an image to upload.'));
  }
}